version: "1.0"
services:
  mysqldb:
    build:
      context: ./Docker/db
      dockerfile: Dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=19021983z
    ports:
      - 3307:3306

  app:
    build:
      context: ./
      dockerfile: Docker/app/Dockerfile
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
        - 8080:8080
    stdin_open: true
    tty: true

